version: '3'
services: 
    auth:
        build: ./auth
        image: auth
        ports:
            - "3000:3000"
    weather:
        build: ./weather
        image: weather
        ports:
            - "5000:5000"
    # proxy:
    #     image: netanelhaber/proxy
    #     ports:
    #         - "8000:8000"
    