version: "3.4"

x-environment: &ports
    - AUTH_PORT=3000
    - WEATHER_PORT=5000
    - PROXY_PORT=8000


services:
    auth:
        build: ./auth
        image: auth
        ports:
            - "3000:3000"
        environment: *ports
    weather:
        build: ./weather
        image: weather
        ports:
            - "5000:5000"
        environment: *ports

    proxy:
        build: ./proxy
        image: proxy
        ports:
            - "8080:8000"
        environment: *ports
